export let users = [
  {
    id: 1,
    name: "name",
    familyname: "famyilyname",
    username: "etml",
    email: "etml@etml.com",
    password: "etml",
    point: 12345,
    level: 48,
    photo: "JSP",
    isadmin: 1,
    fkclan: 1,
  },
  {
    id: 2,
    name: "Derick",
    familyname: "Robert",
    username: "robot",
    email: "Robert@Derick.com",
    password: "eeeeeeeee",
    point: 12345,
    level: 48,
    photo: "JSP",
    isadmin: 1,
    fkclan: 1,
  },
  {
    id: 3,
    name: "ert",
    familyname: "ert",
    username: "ert",
    email: "ert@tzr.com",
    password: "ertzu",
    point: 12345,
    level: 48,
    photo: "JSP",
    isadmin: 1,
    fkclan: 1,
  },
  {
    id: 4,
    name: "wert",
    familyname: "wert",
    username: "wertoto",
    email: "Derick@werno.com",
    password: "wesort",
    point: 12345,
    level: 48,
    photo: "JSP",
    isadmin: 1,
    fkclan: 1,
  },
  {
    id: 5,
    name: "ftu",
    familyname: "ftu",
    username: "futur",
    email: "futur@servai.com",
    password: "drweteghcrtdrthd",
    point: 12345,
    level: 48,
    photo: "JSP",
    isadmin: 1,
    fkclan: 1,
  },
];
