export let users = [
  {
    id: 1,
    name: "daccord",
    familyname: "Admin",
    username: "daccord",
    email: "daccord.admin@daccord.com",
    password: "daccord",
    trophee: 201,
    point: 12345,
    level: 48,
    photo: "JSP",
    isadmin: 1,
    fkClan: 1,
  },
  {
    id: 2,
    name: "Derick",
    familyname: "Robert",
    username: "derrobert",
    email: "derick.robert@etml.com",
    password: "etmlderick2",
    trophee: 199,
    point: 1234,
    level: 23,
    photo: "JSP",
    isadmin: 1,
    fkClan: 2,
  },
  {
    id: 3,
    name: "Christelle",
    familyname: "Labert",
    username: "chrlabert",
    email: "christelle.labert@etml.com",
    password: "etmlchristelle3",
    trophee: 72,
    point: 123,
    level: 5,
    photo: "JSP",
    isadmin: 1,
    fkClan: 3,
  },
  {
    id: 4,
    name: "Fabrice",
    familyname: "Nuget",
    username: "fabnuget",
    email: "fabrice.nuget@etml.com",
    password: "etmlfabrice4",
    trophee: 178,
    point: 1734,
    level: 34,
    photo: "JSP",
    isadmin: 1,
    fkClan: 4,
  },
  {
    id: 5,
    name: "Sarah",
    familyname: "Paraon",
    username: "sarparaon",
    email: "sarah.paraon@etml.com",
    password: "etmlsarah5",
    trophee: 298,
    point: 18338,
    level: 84,
    photo: "JSP",
    isadmin: 1,
    fkClan: 5,
  },
  {
    id: 6,
    name: "Thomas",
    familyname: "Mariet",
    username: "thomariet",
    email: "thomas.mariet@etml.com",
    password: "etmlthomas6",
    trophee: 125,
    point: 1024,
    level: 32,
    photo: "JSP",
    isadmin: 1,
    fkClan: 1,
  },
  {
    id: 7,
    name: "Marion",
    familyname: "Delariet",
    username: "mardelariet",
    email: "marion.delariet@etml.com",
    password: "etmlMarion7",
    trophee: 167,
    point: 1538,
    level: 34,
    photo: "JSP",
    isadmin: 1,
    fkClan: 1,
    fkLigue: 3,
  },
  {
    id: 8,
    name: "Thibaud",
    familyname: "Riack",
    username: "thiriack",
    email: "thibaud.riack@etml.com",
    password: "etmlthibaud8",
    trophee: 246,
    point: 17349,
    level: 64,
    photo: "JSP",
    isadmin: 1,
    fkClan: 2,
    fkLigue: 4,
  },
  {
    id: 9,
    name: "Mattieu",
    familyname: "Rotzberger",
    username: "matrotzberg",
    email: "mattieu.rotzberger@etml.com",
    password: "etmlmattieu9",
    trophee: 154,
    point: 1734,
    level: 26,
    photo: "JSP",
    isadmin: 1,
    fkClan: 3,
    fkLigue: 4,
  },
  {
    id: 10,
    name: "Emma",
    familyname: "Ariback",
    username: "emmariback",
    email: "emma.ariback@etml.com",
    password: "etmlemma10",
    trophee: 116,
    point: 1734,
    level: 21,
    photo: "JSP",
    isadmin: 1,
    fkClan: 4,
    fkRecompenseChoisi: 1,
    fkLigue: 2,
  },
  {
    id: 11,
    name: "Timy",
    familyname: "Jotterand",
    username: "Timy5955",
    email: "timy.jotterand@etml.com",
    password: "etml",
    trophee: 12390,
    point: 2000000000,
    level: 1000,
    photo: "JSP",
    isadmin: 1,
    fkClan: 5,
    fkRecompenseChoisi: 4,
    fkLigue: 3,
  },
];
